# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "publication"
  weight = 40

[[main]]
  name = "Blog"
  url = "https://blog.rahalkar.dev"
  weight = 30

[[main]]
 name = "Talks"
 url = "talk"
 weight = 40

[[main]]
  name = "Awesome Learning"
  url = "awesome-learning"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
[[main]]
   name = "CV"
   url = "files/Resume.pdf"
   weight = 70
